// const ActionTypes = {
//     //USER
//     GET_USERS: 'GET_USERS',
//     GET_USERS_RES: 'GET_USERS_RES',
//     ADD_USER: 'ADD_USER',
//     ADD_USER_RES: 'ADD_USER_RES',
//     UPDATE_USER: 'UPDATE_USER',
//     UPDATE_USER_RES: 'UPDATE_USER_RES',
//     DEL_USER: 'DEL_USER',
//     DEL_USER_RES: 'DEL_USER_RES',
//     UPDATE_PASSWORD: 'UPDATE_PASSWORD',
//     UPDATE_PASSWORD_RES: 'UPDATE_PASSWORD_RES',
//     //PRODUCT
//     GET_PRODUCT: 'GET_PRODUCT',
//     GET_PRODUCT_RES: 'GET_PRODUCT_RES',
//     GET_PRODUCT_ID: 'GET_PRODUCT_ID',
//     GET_PRODUCT_ID_RES: 'GET_PRODUCT_ID_RES',
//     ADD_PRODUCT: 'ADD_PRODUCT',
//     ADD_PRODUCT_RES: 'ADD_PRODUCT_RES',
//     UPDATE_PRODUCT: 'UPDATE_PRODUCT',
//     UPDATE_PRODUCT_RES: 'UPDATE_PRODUCT_RES',
//     DEL_PRODUCT: 'DEL_PRODUCT',
//     DEL_PRODUCT_RES: 'DEL_PRODUCT_RES',
//     //CATEGORY
//     GET_CATEGORY: 'GET_CATEGORY',
//     GET_CATEGORY_RES: 'GET_CATEGORY_RES',
//     //LOGIN
//     REQ_LOGIN: 'REQ_LOGIN',
//     RES_LOGIN: 'RES_LOGIN'
// }

// export default ActionTypes
