const ActionTypes = {
  //User
  REQ_GET_USER: 'REQ_GET_USER',
  RES_GET_USER: 'RES_GET_USER',
  //SignUp
  REQ_GET_SIGNUP: 'REQ_GET_SIGNUP',
  RES_GET_SIGNUP: 'RES_GET_SIGNUP',
  //Login
  REQ_GET_LOGIN: 'REQ_GET_LOGIN',
  GET_LOGIN_RESPONSE: 'GET_LOGIN_RESPONSE',
};

export default ActionTypes;
