const ActionTypes = {
  REQ_GET_EMPLOYEE: 'REQ_GET_EMPLOYEE', //view employee
  GET_EMPLOYEE_RESPONSE: 'GET_EMPLOYEE_RESPONSE',
  REQ_GET_SEARCH: 'REQ_GET_SEARCH', //view search
  GET_SEARCH_RESPONSE: 'GET_SEARCH_RESPONSE',
  REQ_GET_DEPARTMENT: 'REQ_GET_DEPARTMENT', //view department
  GET_DEPARTMENT_RESPONSE: 'GET_DEPARTMENT_RESPONSE',
  REQ_GET_JOROMASTER: 'REQ_GET_JOROMASTER', //view JOROMASTER
  GET_JOROMASTER_RESPONSE: 'GET_JOROMASTER_RESPONSE',
  REQ_GET_USERSROLES: 'REQ_GET_USERSROLES', //view USERSROLES
  GET_USERSROLES_RESPONSE: 'GET_USERSROLES_RESPONSE',
  REQ_GET_JOBTYPE: 'REQ_GET_JOBTYPE', //view jobType
  GET_JOBTYPE_RESPONSE: 'GET_JOBTYPE_RESPONSE',
  REQ_GET_AM: 'REQ_GET_AM', //view AM
  GET_AM_RESPONSE: 'GET_AM_RESPONSE',

  REQ_CREATE_DATA_EMPLOYEE: 'REQ_CREATE_DATA_EMPLOYEE', //create employee
  GET_DATA_EMPLOYEE_RES: 'GET_DATA_EMPLOYEE_RES',

  REQ_TALENTS_EMPLOYEE: ' REQ_TALENTS_EMPLOYEE', //create client contract
  GET_TALENTS_EMPLOYEE_RES: 'GET_TALENTS_EMPLOYEE_RES',

  REQ_UPDATE_EMPLOYEE: 'REQ_UPDATE_EMPLOYEE', //update employee
  GET_UPDATE_EMPLOYEE_RES: 'GET_UPDATE_EMPLOYEE_RES',

  REQ_GET_TALENTS: 'REQ_GET_TALENTS', //view talents
  GET_TALENTS_RESPONSE: 'GET_TALENTS_RESPONSE',
  REQ_GET_TALENTS_JOB: ' REQ_GET_TALENTS_JOB', //view talents Job
  GET_TALENTS_JOB_RESPONSE: 'GET_TALENTS_JOB_RESPONSE',

  REQ_SEARCH_CLIENT: 'REQ_SEARCH_CLIENT', //search client
  GET_CLIENT_RESPONSE: 'GET_CLIENT_RESPONSE',

  REQ_FIND_EMPLOYEE: 'REQ_FIND_EMPLOYEE', //find employee
  GET_FIND_EMPLOYEE_RESPONSE: 'GET_FIND_EMPLOYEE_RESPONSE',
  
  REQ_DEPT_HISTORY: 'REQ_DEPT_HISTORY', //find DEPT HISTORY
  GET_DEPT_HISTORY_RESPONSE: 'GET_DEPT_HISTORY_RESPONSE',
  
  REQ_SALARY_HISTORY: 'REQ_SALARY_HISTORY', //find SALARY HISTORY
  GET_SALARY_HISTORY_RESPONSE: 'GET_SALARY_HISTORY_RESPONSE',


};

export default ActionTypes;
