const ActionType = {
    //Job Post
    REQ_GET_JOBPOST : "REQ_GET_JOBPOST",
    RES_GET_JOBPOST : "RES_GET_JOBPOST",

    REQ_GET_CURNUMBER : "REQ_GET_CURNUMBER",
    RES_GET_CURNUMBER : "RES_GET_CURNUMBER",

    REQ_ADD_JOBPOST : "REQ_ADD_JOBPOST",
    RES_ADD_JOBPOST : "RES_ADD_JOBPOST",

    REQ_UPDATE_JOBPOST : "REQ_UPDATE_JOBPOST",
    RES_UPDATE_JOBPOST : "RES_UPDATE_JOBPOST",

    REQ_DELETE_JOBPOST : "REQ_DELETE_JOBPOST",
    RES_DELETE_JOBPOST : "RES_DELETE_JOBPOST",

    //Client
    REQ_GET_CLIENT : "REQ_GET_CLIENT",
    RES_GET_CLIENT : "RES_GET_CLIENT",

    REQ_ADD_CLIENT : "REQ_ADD_CLIENT",
    RES_ADD_CLIENT : "RES_ADD_CLIENT",

    REQ_UPDATE_CLIENT : "REQ_UPDATE_CLIENT",
    RES_UPDATE_CLIENT : "RES_UPDATE_CLIENT",

    REQ_DELETE_CLIENT : "REQ_DELETE_CLIENT",
    RES_DELETE_CLIENT : "RES_DELETE_CLIENT",

    //Employee Range
    REQ_GET_EMPRANGE : "REQ_GET_EMPRANGE",
    RES_GET_EMPRANGE : "RES_GET_EMPRANGE",
}

export default ActionType;