const ActionTypes = {
    //FINDALL BATCHES
    REQ_GET_BATCHES: 'REQ_GET_BATCHES',
    RES_GET_BATCHES: 'RES_GET_BATCHES' ,

    //CREATE
    REQ_CREATE_BATCH: 'REQ_CREATE_BATCH',
    RES_CREATE_BATCH: 'RES_CREATE_BATCH',

    //FINDALL PROGRAMS
    REQ_GET_PROGRAMS: 'REQ_GET_PROGRAMS',
    RES_GET_PROGRAMS: 'RES_GET_PROGRAMS',

    //FINDALL TRAINERS
    REQ_GET_TRAINERS: 'REQ_GET_TRAINERS',
    RES_GET_TRAINERS: 'RES_GET_TRAINERS',

    //FINDALL TALENTS
    REQ_GET_TALENTS: 'REQ_GET_TALENTS',
    RES_GET_TALENTS: 'RES_GET_TALENTS',

    //UPDATE CLOSEBATCH
    REQ_UPDATE_CLOSE_BATCH: 'REQ_UPDATE_CLOSE_BATCH',
    RES_UPDATE_CLOSE_BATCH: 'RES_UPDATE_CLOSE_BATCH',

    
}

export default ActionTypes
