const ActionTypes = {
    //FINDALL BATCHES
    REQ_GET_BATCHES: 'REQ_GET_BATCHES',
    RES_GET_BATCHES: 'RES_GET_BATCHES' ,

    //CREATE
    REQ_CREATE_BATCH: 'REQ_CREATE_BATCH',
    RES_CREATE_BATCH: 'RES_CREATE_BATCH',

    //FINDALL PROGRAMS
    REQ_GET_PROGRAMS: 'REQ_GET_PROGRAMS',
    RES_GET_PROGRAMS: 'RES_GET_PROGRAMS',

    //FINDALL TRAINERS
    REQ_GET_TRAINERS: 'REQ_GET_TRAINERS',
    RES_GET_TRAINERS: 'RES_GET_TRAINERS',
}

export default ActionTypes
