const ActionTypesSales = {
  GET_CART: 'GET_CART',
  GET_CART_RESPONSE: 'GET_CART_RESPONSE',
  ADD_CART: 'ADD_CART',
  ADD_CART_RES: 'ADD_CART_RES',
  DEL_CART: 'DEL_CART',
  DEL_CART_RES: 'DEL_CART_RES',

  GET_DISKON: 'GET_DISKON',
  GET_DISKON_RES: 'GET_DISKON_RES',

  ADD_ORDER: 'ADD_ORDER',
  ADD_ORDER_RES: 'ADD_ORDER_RES',

  GET_PAYMENT: 'GET_PAYMENT',
  GET_PAYMENT_RES: 'GET_PAYMENT_RES',
};

export default ActionTypesSales;
