const ActionTypes = {
  //SignUp
  REQ_GET_SIGNUP: 'REQ_GET_SIGNUP',
  RES_GET_SIGNUP: 'RES_GET_SIGNUP',

  //Login
  REQ_GET_LOGIN: 'REQ_GET_LOGIN',
  GET_LOGIN_RESPONSE: 'GET_LOGIN_RESPONSE',

  //User
  REQ_GET_USER: 'REQ_GET_USER',
  RES_GET_USER: 'RES_GET_USER',

  //Role
  REQ_GET_ROLE: 'REQ_GET_ROLE',
  RES_GET_ROLE: 'RES_GET_ROLE',

  REQ_UPDATE_ROLE: 'REQ_UPDATE_ROLE',
  RES_UPDATE_ROLE: 'RES_UPDATE_ROLE',

  //Setting
  REQ_GET_PROFILE: 'REQ_GET_PROFILE',
  RES_GET_PROFILE: 'RES_GET_PROFILE',

  REQ_UPDATE_PROFILE: 'REQ_UPDATE_PROFILE',
  RES_UPDATE_PROFILE: 'RES_UPDATE_PROFILE',

  REQ_UPDATE_PASSWORD: 'REQ_UPDATE_PASSWORD',
  RES_UPDATE_PASSWORD: 'RES_UPDATE_PASSWORD',

  REQ_ADD_EMAIL: 'REQ_ADD_EMAIL',
  RES_ADD_EMAIL: 'RES_ADD_EMAIL',

  REQ_UPDATE_EMAIL: 'REQ_UPDATE_EMAIL',
  RES_UPDATE_EMAIL: 'RES_UPDATE_EMAIL',

  REQ_DELETE_EMAIL: 'REQ_DELETE_EMAIL',
  RES_DELETE_EMAIL: 'RES_DELETE_EMAIL',

  REQ_ADD_PHONE: 'REQ_ADD_PHONE',
  RES_ADD_PHONE: 'RES_ADD_PHONE',

  REQ_UPDATE_PHONE: 'REQ_UPDATE_PHONE',
  RES_UPDATE_PHONE: 'RES_UPDATE_PHONE',

  REQ_DELETE_PHONE: 'REQ_DELETE_PHONE',
  RES_DELETE_PHONE: 'RES_DELETE_PHONE',

  REQ_GET_ADDRESS_TYPE: 'REQ_GET_ADDRESS_TYPE',
  RES_GET_ADDRESS_TYPE: 'RES_GET_ADDRESS_TYPE',

  REQ_GET_CITY: 'REQ_GET_CITY',
  RES_GET_CITY: 'RES_GET_CITY',

  REQ_ADD_ADDRESS: 'REQ_ADD_ADDRESS',
  RES_ADD_ADDRESS: 'RES_ADD_ADDRESS',

  REQ_UPDATE_ADDRESS: 'REQ_UPDATE_ADDRESS',
  RES_UPDATE_ADDRESS: 'RES_UPDATE_ADDRESS',

  REQ_DELETE_ADDRESS: 'REQ_DELETE_ADDRESS',
  RES_DELETE_ADDRESS: 'RES_DELETE_ADDRESS',

  REQ_ADD_EDUCATION: 'REQ_ADD_EDUCATION',
  RES_ADD_EDUCATION: 'RES_ADD_EDUCATION',

  REQ_UPDATE_EDUCATION: 'REQ_UPDATE_EDUCATION',
  RES_UPDATE_EDUCATION: 'RES_UPDATE_EDUCATION',

  REQ_DELETE_EDUCATION: 'REQ_DELETE_EDUCATION',
  RES_DELETE_EDUCATION: 'RES_DELETE_EDUCATION',

  REQ_ADD_EXPERIENCES: 'REQ_ADD_EXPERIENCES',
  RES_ADD_EXPERIENCES: 'RES_ADD_EXPERIENCES',

  REQ_UPDATE_EXPERIENCES: 'REQ_UPDATE_EXPERIENCES',
  RES_UPDATE_EXPERIENCES: 'RES_UPDATE_EXPERIENCES',

  REQ_DELETE_EXPERIENCES: 'REQ_DELETE_EXPERIENCES',
  RES_DELETE_EXPERIENCES: 'RES_DELETE_EXPERIENCES',

  REQ_GET_SKILL: 'REQ_GET_SKILL',
  RES_GET_SKILL: 'RES_GET_SKILL',

  REQ_ADD_SKILL: 'REQ_ADD_SKILL',
  RES_ADD_SKILL: 'RES_ADD_SKILL',

  REQ_DELETE_SKILL: 'REQ_DELETE_SKILL',
  RES_DELETE_SKILL: 'RES_DELETE_SKILL',

  //Apply Job
  REQ_APPLY_JOB: 'REQ_APPLY_JOB',
  RES_APPLY_JOB: 'RES_APPLY_JOB',
};

export default ActionTypes;
