const ActionTypes = {
  //SignUp
  REQ_GET_SIGNUP: 'REQ_GET_SIGNUP',
  RES_GET_SIGNUP: 'RES_GET_SIGNUP',

  //Login
  REQ_GET_LOGIN: 'REQ_GET_LOGIN',
  GET_LOGIN_RESPONSE: 'GET_LOGIN_RESPONSE',

  //User
  REQ_GET_USER: 'REQ_GET_USER',
  RES_GET_USER: 'RES_GET_USER',

  //Setting
  REQ_GET_PROFILE: 'REQ_GET_PROFILE',
  RES_GET_PROFILE: 'RES_GET_PROFILE',

  REQ_UPDATE_PROFILE: 'REQ_UPDATE_PROFILE',
  RES_UPDATE_PROFILE: 'RES_UPDATE_PROFILE',

  REQ_UPDATE_PASSWORD: 'REQ_UPDATE_PASSWORD',
  RES_UPDATE_PASSWORD: 'RES_UPDATE_PASSWORD',

  REQ_ADD_EMAIL: 'REQ_ADD_EMAIL',
  RES_ADD_EMAIL: 'RES_ADD_EMAIL',

  REQ_UPDATE_EMAIL: 'REQ_UPDATE_EMAIL',
  RES_UPDATE_EMAIL: 'RES_UPDATE_EMAIL',

  REQ_DELETE_EMAIL: 'REQ_DELETE_EMAIL',
  RES_DELETE_EMAIL: 'RES_DELETE_EMAIL',
};

export default ActionTypes;
