const ActionType = {

    REQ_GET_EDUCATION : "REQ_GET_EDUCATION",
    RES_GET_EDUCATION : "RES_GET_EDUCATION",
    
    REQ_GET_WORKTYPE : "REQ_GET_WORKTYPE",
    RES_GET_WORKTYPE : "RES_GET_WORKTYPE",
    
    REQ_GET_JOBROLE : "REQ_GET_JOBROLE",
    RES_GET_JOBROLE : "RES_GET_JOBROLE",
    
    REQ_GET_INDUSTRY : "REQ_GET_INDUSTRY",
    RES_GET_INDUSTRY : "RES_GET_INDUSTRY",

    REQ_GET_CITY : "REQ_GET_CITY",
    RES_GET_CITY : "RES_GET_CITY",

}
export default ActionType