const ActionTypes = {
  //     //USER
  //     GET_USERS: 'GET_USERS',
  //     GET_USERS_RES: 'GET_USERS_RES',
  //     ADD_USER: 'ADD_USER',
  //     ADD_USER_RES: 'ADD_USER_RES',
  //     UPDATE_USER: 'UPDATE_USER',
  //     UPDATE_USER_RES: 'UPDATE_USER_RES',
  //     DEL_USER: 'DEL_USER',
  //     DEL_USER_RES: 'DEL_USER_RES',
  //     UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  //     UPDATE_PASSWORD_RES: 'UPDATE_PASSWORD_RES',
  //     //PRODUCT
  //     GET_PRODUCT: 'GET_PRODUCT',
  //     GET_PRODUCT_RES: 'GET_PRODUCT_RES',
  //     GET_PRODUCT_ID: 'GET_PRODUCT_ID',
  //     GET_PRODUCT_ID_RES: 'GET_PRODUCT_ID_RES',
  //     ADD_PRODUCT: 'ADD_PRODUCT',
  //     ADD_PRODUCT_RES: 'ADD_PRODUCT_RES',
  //     UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  //     UPDATE_PRODUCT_RES: 'UPDATE_PRODUCT_RES',
  //     DEL_PRODUCT: 'DEL_PRODUCT',
  //     DEL_PRODUCT_RES: 'DEL_PRODUCT_RES',
  //     //CATEGORY
  //     GET_CATEGORY: 'GET_CATEGORY',
  //     GET_CATEGORY_RES: 'GET_CATEGORY_RES',
  //     //LOGIN
  //     REQ_LOGIN: 'REQ_LOGIN',
  //     RES_LOGIN: 'RES_LOGIN'

  //bank
  REQ_GET_BANK: 'REQ_GET_BANK',
  GET_BANK_RESPONE: 'GET_BANK_RESPONE',

  ADD_BANK: 'ADD_BANK',
  ADD_BANK_RESPONSE: 'ADD_BANK_RESPONSE',

  UPDATE_BANK: 'UPDATE_BANK',
  UPDATE_BANK_RESPONSE: 'UPDATE_BANK_RESPONSE',

  DELETE_BANK: 'DELETE_BANK',
  DELETE_BANK_RESPONSE: 'DELETE_BANK_RESPONSE',

  REG_GET_BANK_ID: 'REG_GET_BANK_ID',
  GET_BANK_ID_RESPONSE: 'GET_BANK_ID_RESPONSE',


  //fintech
  REQ_GET_FINTECH: 'REQ_GET_FINTECH',
  GET_FINTECH_RESPONE: 'GET_FINTECH_RESPONE',

  ADD_FINTECH: 'ADD_FINTECH',
  ADD_FINTECH_RESPONSE: 'ADD_FINTECH_RESPONSE',

  UPDATE_FINTECH: 'UPDATE_FINTECH',
  UPDATE_FINTECH_RESPONSE: 'UPDATE_FINTECH_RESPONSE',

  DELETE_FINTECH: 'DELETE_FINTECH',
  DELETE_FINTECH_RESPONSE: 'DELETE_FINTECH_RESPONSE',


  //account
  REQ_GET_ACCOUNT: 'REQ_GET_ACCOUNT',
  GET_ACCOUNT_RESPONE: 'GET_ACCOUNT_RESPONE',

  ADD_ACCOUNT: 'ADD_ACCOUNT',
  ADD_ACCOUNT_RESPONSE: 'ADD_ACCOUNT_RESPONSE',

  UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
  UPDATE_ACCOUNT_RESPONSE: 'UPDATE_ACCOUNT_RESPONSE',

  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  DELETE_ACCOUNT_RESPONSE: 'DELETE_ACCOUNT_RESPONSE',

     //TOPUP
     ADD_TOPUP :'ADD_TOPUP',
     ADD_TOPUP_RESPONSE: 'ADD_TOPUP_RESPONSE',
 
 
     //TRANSACTION
     REQ_GET_TRANSACTION: 'REQ_GET_TRANSACTION',
     GET_TRANSACTION_RESPONE: 'GET_TRANSACTION_RESPONE',
};

export default ActionTypes;
