const ActionTypeCurr = {
  GET_CURRICULUM: 'GET_CURRICULUM',
  GET_CURRICULUM_RES: 'GET_CURRICULUM_RES',

  ADD_CURRICULUM: 'ADD_CURRICULUM',
  ADD_CURRICULUM_RES: 'ADD_CURRICULUM_RES',

  ADD_SECTION: 'ADD_SECTION',
  ADD_SECTION_RES: 'ADD_SECTION_RES',

  ADD_SECTION_DETAIL: 'ADD_SECTION_DETAIL',
  ADD_SECTION_DETAIL_RES: 'ADD_SECTION_DETAIL_RES',

  UPDATE_CURRICULUM: 'UPDATE_CURRICULUM',
  UPDATE_CURRICULUM_RES: 'UPDATE_CURRICULUM_RES',

  GET_CURRNUMBER: 'GET_CURRNUMBER',
  GET_CURRNUMBER_RES: 'GET_CURRNUMBER_RES',

  VIEW_SECTION: 'VIEW_SECTION',
  VIEW_SECTION_RES: 'VIEW_SECTION_RES',

  GET_SECTION_UP: 'GET_SECTION_UP',
  GET_SECTION_UP_RES: 'GET_SECTION_UP_RES',

  GET_CURR_BY_ID: 'GET_CURR_BY_ID',
  GET_CURR_BY_ID_RES: 'GET_CURR_BY_ID_RES',

  GET_SECT_MERGE: 'GET_SECT_MERGE',
  GET_SECT_MERGE_RES: 'GET_SECT_MERGE_RES',

  GET_ALL: 'GET_ALL',
  GET_ALL_RES: 'GET_ALL_RES',

  GET_INSTRUCTOR: 'GET_INSTRUCTOR',
  GET_INSTRUCTOR_RES: 'GET_INSTRUCTOR_RES',
};

export default ActionTypeCurr;
