const ActionTypes = {
    GET_CURRICULUM: 'GET_CURRICULUM',
    GET_CURRICULUM_RES: 'GET_CURRICULUM_RES',
    ADD_CURRICULUM: 'ADD_CURRICULUM',
    ADD_CURRICULUM_RES: 'ADD_CURRICULUM_RES',
    ADD_SECTION: 'ADD_SECTION',
    ADD_SECTION_RES: 'ADD_SECTION_RES',
    ADD_SECTION_DETAIL: 'ADD_SECTION_DETAIL',
    ADD_SECTION_DETAIL_RES: 'ADD_SECTION_DETAIL_RES',
    UPDATE_CURRICULUM: 'UPDATE_CURRICULUM',
    UPDATE_CURRICULUM_RES: 'UPDATE_CURRICULUM_RES',
    GET_CURRNUMBER: 'GET_CURRNUMBER',
    GET_CURRNUMBER_RES: 'GET_CURRNUMBER_RES',
    VIEW_SECTION: 'VIEW_SECTION',
    VIEW_SECTION_RES: 'VIEW_SECTION_RES',
    VIEW_SECTION_DETAIL: 'VIEW_SECTION_DETAIL',
    VIEW_SECTION_DETAIL_RES: 'VIEW_SECTION_DETAIL_RES'
}

export default ActionTypes