const ActionType = {
    //Job Post
    REQ_GET_JOBPOST : "REQ_GET_JOBPOST",
    RES_GET_JOBPOST : "RES_GET_JOBPOST",

    REQ_GET_JOBBYID : "REQ_GET_JOBBYID",
    RES_GET_JOBBYID : "RES_GET_JOBBYID",

    REQ_GET_JOBPHOTO : "REQ_GET_JOBPHOTO",
    RES_GET_JOBPHOTO : "RES_GET_JOBPHOTO",

    REQ_GET_CURNUMBER : "REQ_GET_CURNUMBER",
    RES_GET_CURNUMBER : "RES_GET_CURNUMBER",

    REQ_ADD_JOBPOST : "REQ_ADD_JOBPOST",
    RES_ADD_JOBPOST : "RES_ADD_JOBPOST",

    REQ_UPDATE_JOBPOST : "REQ_UPDATE_JOBPOST",
    RES_UPDATE_JOBPOST : "RES_UPDATE_JOBPOST",

    REQ_DELETE_JOBPOST : "REQ_DELETE_JOBPOST",
    RES_DELETE_JOBPOST : "RES_DELETE_JOBPOST",

    REQ_UPDATE_STATUS : "REQ_UPDATE_STATUS",
    RES_UPDATE_STATUS : "RES_UPDATE_STATUS",

    REQ_SEARCH_JOBPOST : "REQ_SEARCH_JOBPOST",
    RES_SEARCH_JOBPOST : "RES_SEARCH_JOBPOST",

    //Talent Apply
    REQ_GET_CANDIDATE : "REQ_GET_CANDIDATE",
    RES_GET_CANDIDATE : "RES_GET_CANDIDATE",

    REQ_UPDATE_CANDIDATE : "REQ_UPDATE_CANDIDATE",
    RES_UPDATE_CANDIDATE : "RES_UPDATE_CANDIDATE",

    //Client
    REQ_GET_CLIENT : "REQ_GET_CLIENT",
    RES_GET_CLIENT : "RES_GET_CLIENT",

    REQ_GET_CLIENTBYID : "REQ_GET_CLIENTBYID",
    RES_GET_CLIENTBYID : "RES_GET_CLIENTBYID",

    REQ_ADD_CLIENT : "REQ_ADD_CLIENT",
    RES_ADD_CLIENT : "RES_ADD_CLIENT",

    REQ_UPDATE_CLIENT : "REQ_UPDATE_CLIENT",
    RES_UPDATE_CLIENT : "RES_UPDATE_CLIENT",

    REQ_DELETE_CLIENT : "REQ_DELETE_CLIENT",
    RES_DELETE_CLIENT : "RES_DELETE_CLIENT",

    //Employee Range
    REQ_GET_EMPRANGE : "REQ_GET_EMPRANGE",
    RES_GET_EMPRANGE : "RES_GET_EMPRANGE",

    RESET_STATE : "RESET_STATE"
}

export default ActionType;